{% set name = "xtensor-zarr" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xtensor-stack/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ce02f4262b14765cfb893471dbcec37ec3be77059eff425dd34179bd9e80e9ae

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - zarray >=0.1,<0.2
    - xtensor >=0.23.8,<0.24
    - xtensor-io >=0.12.7,<0.13
    - nlohmann_json >=3.9.1,<3.10
    - gdal >=3.0,<3.1
    - zlib >=1.2.11,<1.3
    - blosc >=1.21.0,<1.22
    - cpp-filesystem >=1.3,<1.4
  run:
    # header-only packages don't have
    # a run_exports section
    - {{ pin_compatible('zarray', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - {{ pin_compatible('xtensor-io', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x') }}
    - {{ pin_compatible('cpp-filesystem', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-zarr  # [unix]
    - test -f ${PREFIX}/include/xtensor-zarr/xzarr_hierarchy.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-zarr/xtensor-zarrConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-zarr/xtensor-zarrConfigVersion.cmake  # [unix]
    - test -e ${PREFIX}/lib/libxtensor-zarr-gdal${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-zarr\xzarr_hierarchy.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-zarr\xtensor-zarrConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-zarr\xtensor-zarrConfigVersion.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_LIB%\\libxtensor-zarr-gdal.lib (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor-zarr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of the Zarr version 3.0 core protocol based on xtensor
  description: This library enables loading chunked arrays stored in the Zarr format, in various formats and file systems.
  doc_url: https://xtensor-zarr.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-zarr

extra:
  recipe-maintainers:
    - davidbrochart
    - JohanMabille
    - conda-forge/xtensor
